
export const TRANSLATIONS = {
  en: {
    appName: "Chatty AI",
    tagline: "Your Personal Intelligent Assistant",
    startChatting: "Start Chatting",
    loginWithGoogle: "Login with Google",
    home: "Home",
    stories: "Stories",
    food: "Ultimate Alchemy",
    imageGen: "Image Generator",
    summaries: "Summaries",
    settings: "Settings",
    profile: "Profile",
    subscribe: "Subscribe",
    premium: "Premium",
    typeAMessage: "Type a message...",
    clearChat: "Clear Chat",
    logout: "Logout",
    upgradeDesc: "Unlock unlimited generations, faster processing, and offline mode.",
    save: "Save",
    generate: "Generate",
    ingredientsPlaceholder: "List your ingredients (e.g., eggs, tomato, bread)...",
    storyThemePlaceholder: "Type a story theme...",
    summaryPlaceholder: "Paste text or YouTube link...",
    recentConversations: "Recent Chats",
    newChat: "New Chat",
    language: "Language",
    darkMode: "Dark Mode",
    subscriptionStatus: "Status",
    free: "Free Plan",
    pro: "Pro Plan",
    welcome: "Welcome back",
    fetching: "Thinking...",
    noMessages: "Start a conversation!",
    arabic: "العربية",
    english: "English",
    switchLang: "Switch Language",
    summonChatty: "Summon Chatty",
    listening: "Listening...",
    themeToggle: "Toggle Theme"
  },
  ar: {
    appName: "شاتي ذكاء اصطناعي",
    tagline: "مساعدك الشخصي الذكي",
    startChatting: "ابدأ الدردشة",
    loginWithGoogle: "تسجيل الدخول باستخدام جوجل",
    home: "الرئيسية",
    stories: "قصص",
    food: "الكيمياء القصوى",
    imageGen: "مولد الصور",
    summaries: "الملخصات",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    subscribe: "اشتراك",
    premium: "بريميوم",
    typeAMessage: "اكتب رسالة...",
    clearChat: "مسح المحادثة",
    logout: "تسجيل الخروج",
    upgradeDesc: "افتح أجيالاً غير محدودة، ومعالجة أسرع، ووضع عدم الاتصال.",
    save: "حفظ",
    generate: "توليد",
    ingredientsPlaceholder: "اذكر المكونات (مثلاً: بيض، طماطم، خبز)...",
    storyThemePlaceholder: "اكتب موضوع القصة...",
    summaryPlaceholder: "انسق النص أو رابط يوتيوب...",
    recentConversations: "المحادثات الأخيرة",
    newChat: "محادثة جديدة",
    language: "الغة",
    darkMode: "الوضع الداكن",
    subscriptionStatus: "الحالة",
    free: "الخطة المجانية",
    pro: "خطة برو",
    welcome: "مرحباً بعودتك",
    fetching: "جارٍ التفكير...",
    noMessages: "ابدأ محادثة!",
    arabic: "العربية",
    english: "English",
    switchLang: "تبديل اللغة",
    summonChatty: "استدعاء شاتي",
    listening: "جاري الاستماع...",
    themeToggle: "تبديل المظهر"
  }
};
